import type { Plan } from '../types/domain'
import dayImage from '../assets/images/plans/navigo_day.svg'
import weekImage from '../assets/images/plans/navigo_week.svg'
import monthImage from '../assets/images/plans/navigo_month.svg'
import yearlyImage from '../assets/images/plans/navigo_yearly.svg'
import seniorImage from '../assets/images/plans/navigo_senior.svg'
import libertyPlusImage from '../assets/images/plans/liberty_plus.svg'
import studentImage from '../assets/images/plans/imagine_r_student.svg'
import schoolImage from '../assets/images/plans/imagine_r_school.svg'
import juniorImage from '../assets/images/plans/imagine_r_junior.svg'
import solidarityImage from '../assets/images/plans/navigo_solidarity_75.svg'
import discountImage from '../assets/images/plans/navigo_discount_50.svg'
import freeImage from '../assets/images/plans/navigo_free.svg'
import amethystImage from '../assets/images/plans/amethyst.svg'
import metroTicketImage from '../assets/images/plans/ticket_metro.svg'
import busTramTicketImage from '../assets/images/plans/ticket_bus_tram.svg'
import onboardTicketImage from '../assets/images/plans/ticket_onboard.svg'
import airportTicketImage from '../assets/images/plans/ticket_airport.svg'
import parisVisiteImage from '../assets/images/plans/paris_visite.svg'
import scolrImage from '../assets/images/plans/carte_scolr.svg'
import scolaireBusImage from '../assets/images/plans/carte_scolaire_bus.svg'
import civicImage from '../assets/images/plans/discount_50_civic.svg'
import handicapPersonImage from '../assets/images/plans/handicap_person.svg'
import handicapCompanionImage from '../assets/images/plans/handicap_companion.svg'

export const SINGLE_TICKET_PRICE = 2.10
/** Navigo Liberte+ price per trip, minimum 2026 fare. */
export const LIBERTE_PLUS_PRICE_PER_TRIP = 1.64
/** Canonical IDFM fare catalog URL. */
export const IDFM_FARES_URL = 'https://www.iledefrance-mobilites.fr/titres-et-tarifs'

/**
 * Navigo, Imagine R, and solidarity plan catalog for 2026.
 * Official source: Ile-de-France Mobilites, January 2026.
 *
 * Key fields:
 *  - `type`: billing cadence
 *  - `eligible(p)`: rich predicate based on CSS, ASS, AME, RSA, and apprentice flags
 *  - `priority`: default sort order, lower values first
 */
export const PLANS: Plan[] = [
  {
    id: 'navigo_day',
    name: 'Navigo Jour',
    type: 'day',
    description: 'Voyager en illimite pendant une journee entiere.',
    image: dayImage,
    priority: 60,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['employee', 'student', 'senior'],
    yearlyPrice: null,
    monthlyPrice: null,
    unitPrice: 12.30,
    zones: { min: 1, max: 5 },
    renewal: 'day',
    requiredDocuments: [],
    condition: ({ daysPerWeek }) => daysPerWeek <= 1,
    eligible: () => true,
  },
  {
    id: 'navigo_week',
    name: 'Navigo Semaine',
    type: 'weekly',
    description: 'Voyager en illimite toute la semaine.',
    image: weekImage,
    priority: 50,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['employee', 'student', 'senior'],
    yearlyPrice: 32.40 * 52,
    monthlyPrice: 32.40 * (52 / 12),
    unitPrice: 32.40,
    zones: { min: 1, max: 5 },
    renewal: 'weekly',
    requiredDocuments: [],
    condition: ({ daysPerWeek }) => daysPerWeek <= 3,
    eligible: () => true,
  },
  {
    id: 'navigo_month',
    name: 'Navigo Mois',
    type: 'monthly',
    description: 'Voyager en illimite tout le mois, sans engagement annuel.',
    image: monthImage,
    priority: 40,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['employee', 'student', 'senior'],
    yearlyPrice: 1089.60,
    monthlyPrice: 90.80,
    zones: { min: 1, max: 5 },
    renewal: 'monthly',
    requiredDocuments: [],
    condition: ({ daysPerWeek }) => daysPerWeek >= 2,
    eligible: () => true,
    employerRefund: 0.5,
  },
  {
    id: 'navigo_yearly',
    name: 'Navigo Annuel',
    type: 'yearly',
    description: 'Voyager toute l\'année avec le 12e mois inclus.',
    image: yearlyImage,
    priority: 30,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['employee', 'student', 'senior'],
    yearlyPrice: 90.80 * 11,
    monthlyPrice: 90.80,
    zones: { min: 1, max: 5 },
    renewal: 'yearly',
    requiredDocuments: [],
    condition: ({ daysPerWeek }) => daysPerWeek >= 4,
    eligible: () => true,
    employerRefund: 0.5,
  },
  {
    id: 'navigo_senior',
    name: 'Navigo Senior',
    type: 'yearly',
    description: 'Tarif preferentiel pour les 62 ans et plus.',
    image: seniorImage,
    priority: 25,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['senior'],
    yearlyPrice: 544.80,
    monthlyPrice: 45.40,
    zones: { min: 1, max: 5 },
    renewal: 'yearly',
    requiredDocuments: ['identity_document'],
    condition: ({ age }) => (age ?? 0) >= 62,
    eligible: ({ age, flags }) => (age ?? 0) >= 62 || !!flags?.isRetired,
  },
  {
    id: 'imagine_r_student',
    name: 'Imagine R Etudiant',
    type: 'yearly',
    description: 'Le forfait indispensable des etudiants en Ile-de-France.',
    image: studentImage,
    priority: 20,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['student'],
    yearlyPrice: 392.30,
    monthlyPrice: 392.30 / 12,
    zones: { min: 1, max: 5 },
    renewal: 'yearly',
    requiredDocuments: ['school_certificate'],
    condition: ({ age }) => (age ?? 0) >= 18 && (age ?? 0) <= 25,
    eligible: ({ age, flags }) => !!flags?.isStudent && (age ?? 0) < 26,
  },
  {
    id: 'imagine_r_school',
    name: 'Imagine R Scolaire',
    type: 'yearly',
    description: 'Le forfait annuel des jeunes du primaire, du secondaire et des apprentis.',
    image: schoolImage,
    priority: 20,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['school'],
    yearlyPrice: 392.30,
    monthlyPrice: 392.30 / 12,
    zones: { min: 1, max: 5 },
    renewal: 'yearly',
    requiredDocuments: ['school_certificate'],
    condition: ({ age }) => (age ?? 0) >= 11 && (age ?? 0) <= 25,
    eligible: ({ age, flags }) => (age ?? 0) >= 11 && (age ?? 0) < 26 && (!!flags?.isApprentice || !flags?.isStudent),
  },
  {
    id: 'imagine_r_junior',
    name: 'Imagine R Junior',
    type: 'yearly',
    description: 'Imagine R a un prix tres avantageux pour les moins de 11 ans.',
    image: juniorImage,
    priority: 20,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['junior_school'],
    yearlyPrice: 24.80,
    monthlyPrice: 24.80 / 12,
    zones: { min: 1, max: 5 },
    renewal: 'yearly',
    requiredDocuments: ['family_record_book', 'school_certificate'],
    condition: ({ age }) => (age ?? 0) < 11,
    eligible: ({ age }) => (age ?? 0) < 11,
  },
  {
    id: 'liberty_plus',
    name: 'Navigo Liberte+',
    type: 'usage',
    description: 'Payez vos trajets a l\'unité, des 1,64 EUR par trajet, toutes zones.',
    image: libertyPlusImage,
    priority: 45,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['employee', 'student', 'senior'],
    yearlyPrice: null,
    monthlyPrice: null,
    zones: { min: 1, max: 5 },
    renewal: 'usage',
    requiredDocuments: [],
    condition: ({ daysPerWeek }) => daysPerWeek <= 2,
    eligible: () => true,
  },
  {
    id: 'navigo_solidarity_75',
    name: 'Solidarite 75%',
    type: 'monthly',
    description: 'Reduction de 75% pour les beneficiaires CSS sans participation ou ASS.',
    image: solidarityImage,
    priority: 15,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['solidarity'],
    yearlyPrice: 22.70 * 12,
    monthlyPrice: 22.70,
    zones: { min: 1, max: 5 },
    renewal: 'monthly',
    requiredDocuments: ['caf_certificate', 'tax_notice'],
    eligible: ({ flags }) => !!flags?.hasCssWithoutCopay || !!flags?.hasASS,
  },
  {
    id: 'navigo_discount_50',
    name: 'Reduction 50%',
    type: 'monthly',
    description: 'Reduction de 50% pour les beneficiaires AME.',
    image: discountImage,
    priority: 18,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['solidarity'],
    yearlyPrice: 45.40 * 12,
    monthlyPrice: 45.40,
    zones: { min: 1, max: 5 },
    renewal: 'monthly',
    requiredDocuments: ['caf_certificate', 'tax_notice'],
    eligible: ({ flags }) => !!flags?.hasAME,
  },
  {
    id: 'navigo_free',
    name: 'Gratuite Transport',
    type: 'monthly',
    description: 'Transport gratuit pour les beneficiaires RSA eligibles ou ASS avec CSS sans participation.',
    image: freeImage,
    priority: 10,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['solidarity'],
    yearlyPrice: 0,
    monthlyPrice: 0,
    zones: { min: 1, max: 5 },
    renewal: 'monthly',
    requiredDocuments: ['caf_certificate', 'tax_notice'],
    eligible: ({ flags }) => !!flags?.hasRSA || (!!flags?.hasASS && !!flags?.hasCssWithoutCopay),
  },
  {
    id: 'amethyst',
    name: 'Amethyste',
    type: 'yearly',
    description: 'Forfait pour les personnes en situation de handicap, selon le departement.',
    image: amethystImage,
    priority: 22,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['amethyst'],
    yearlyPrice: null,
    monthlyPrice: null,
    zones: { min: 1, max: 5 },
    renewal: 'yearly',
    requiredDocuments: ['disability_card', 'mdph_notice'],
    eligible: () => true,
  },

  // --- Tickets et titres unitaires (catalogue uniquement, hors simulateur) ---
  {
    id: 'ticket_metro',
    name: 'Ticket Metro-Train-RER',
    type: 'usage',
    description: 'Effectuez votre trajet en metro, train ou RER.',
    image: metroTicketImage,
    priority: 70,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['employee', 'student', 'senior'],
    yearlyPrice: null,
    monthlyPrice: null,
    unitPrice: 2.55,
    zones: { min: 1, max: 5 },
    renewal: 'usage',
    requiredDocuments: [],
    condition: () => false,
    eligible: () => false,
  },
  {
    id: 'ticket_bus_tram',
    name: 'Ticket Bus-Tram',
    type: 'usage',
    description: 'Effectuez votre trajet en bus ou tram.',
    image: busTramTicketImage,
    priority: 71,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['employee', 'student', 'senior'],
    yearlyPrice: null,
    monthlyPrice: null,
    unitPrice: 2.05,
    zones: { min: 1, max: 5 },
    renewal: 'usage',
    requiredDocuments: [],
    condition: () => false,
    eligible: () => false,
  },
  {
    id: 'ticket_onboard',
    name: "Ticket d'acces a bord",
    type: 'usage',
    description: 'Payez votre trajet par carte bancaire directement a bord du bus.',
    image: onboardTicketImage,
    priority: 72,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['employee', 'student', 'senior'],
    yearlyPrice: null,
    monthlyPrice: null,
    unitPrice: 2.50,
    zones: { min: 1, max: 5 },
    renewal: 'usage',
    requiredDocuments: [],
    condition: () => false,
    eligible: () => false,
  },
  {
    id: 'ticket_airport',
    name: 'Ticket Paris Region <> Aeroports',
    type: 'usage',
    description: 'Aller ou partir des aeroports Orly ou CDG.',
    image: airportTicketImage,
    priority: 73,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['employee', 'student', 'senior'],
    yearlyPrice: null,
    monthlyPrice: null,
    unitPrice: 14,
    zones: { min: 1, max: 5 },
    renewal: 'usage',
    requiredDocuments: [],
    condition: () => false,
    eligible: () => false,
  },
  {
    id: 'paris_visite',
    name: 'Forfait Paris Visite',
    type: 'day',
    description: 'Votre allie si vous passez quelques jours dans la capitale.',
    image: parisVisiteImage,
    priority: 74,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['employee', 'student', 'senior'],
    yearlyPrice: null,
    monthlyPrice: null,
    priceLabel: 'des 30,60 EUR/jour',
    zones: { min: 1, max: 5 },
    renewal: 'day',
    requiredDocuments: [],
    condition: () => false,
    eligible: () => false,
  },
  {
    id: 'carte_scolr',
    name: "Carte Scol'R",
    type: 'yearly',
    description: 'La carte pour les circuits scolaires speciaux.',
    image: scolrImage,
    priority: 75,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['school', 'junior_school'],
    yearlyPrice: 354.78,
    monthlyPrice: null,
    zones: { min: 1, max: 5 },
    renewal: 'yearly',
    requiredDocuments: [],
    condition: () => false,
    eligible: () => false,
  },
  {
    id: 'carte_scolaire_bus',
    name: 'Carte scolaire bus lignes regulieres',
    type: 'yearly',
    description: 'Facilitez vos trajets scolaires quotidiens en bus.',
    image: scolaireBusImage,
    priority: 76,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['school', 'junior_school'],
    yearlyPrice: null,
    monthlyPrice: null,
    priceVariable: true,
    zones: { min: 1, max: 5 },
    renewal: 'yearly',
    requiredDocuments: [],
    condition: () => false,
    eligible: () => false,
  },
  {
    id: 'discount_50_civic',
    name: 'Reduction 50% Volontaires du Service civique',
    type: 'monthly',
    description: 'La reduction pour les volontaires du Service Civique.',
    image: civicImage,
    priority: 77,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['student', 'solidarity'],
    yearlyPrice: null,
    monthlyPrice: null,
    priceLabel: '-50 %',
    zones: { min: 1, max: 5 },
    renewal: 'monthly',
    requiredDocuments: [],
    condition: () => false,
    eligible: () => false,
  },
  {
    id: 'handicap_person',
    name: 'Forfaits ou titres personne en situation de handicap',
    type: 'yearly',
    description: 'Reduction 50% ou gratuite pour les personnes en situation de handicap.',
    image: handicapPersonImage,
    priority: 23,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['amethyst'],
    yearlyPrice: 0,
    monthlyPrice: 0,
    zones: { min: 1, max: 5 },
    renewal: 'yearly',
    requiredDocuments: ['disability_card', 'mdph_notice'],
    condition: () => false,
    eligible: () => false,
  },
  {
    id: 'handicap_companion',
    name: 'Forfaits ou titres accompagnant handicap',
    type: 'yearly',
    description: 'Gratuite ou tarif reduit pour votre accompagnant.',
    image: handicapCompanionImage,
    priority: 24,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['amethyst'],
    yearlyPrice: 0,
    monthlyPrice: 0,
    zones: { min: 1, max: 5 },
    renewal: 'yearly',
    requiredDocuments: [],
    condition: () => false,
    eligible: () => false,
  },
]
