import type { Offer } from '../types/domain'

export const SINGLE_TICKET_PRICE = 2.1

export const DOCUMENT_LABELS: Record<string, string> = {
  identity_document: "Piece d'identite (CNI, passeport)",
  family_record: 'Livret de famille ou acte de naissance',
  school_certificate: 'Certificat de scolarite, annee en cours',
  scholarship_certificate: "Attestation d'attribution de bourse",
  caf_certificate: 'Attestation CAF, quotient familial',
  tax_notice: "Avis d'imposition ou de non-imposition",
  disability_card: "Carte d'invalidite ou notification MDPH",
  mdph_notice: 'Notification de decision MDPH',
}

export const OFFERS: Offer[] = [
  {
    id: 'navigo_annual',
    name: 'Navigo Annuel',
    description: "L'abonnement annuel tout reseau, ideal pour les usages reguliers.",
    profiles: ['employee', 'student', 'senior'],
    yearlyPrice: 902.4,
    monthlyPrice: 75.2,
    zones: { min: 1, max: 5 },
    renewalFrequency: 'annual',
    requiredDocuments: [],
    condition: ({ weeklyUsageDays }) => weeklyUsageDays >= 4,
    employerRefundRate: 0.5,
  },
  {
    id: 'navigo_senior',
    name: 'Navigo Annuel Senior',
    description: 'Tarif preferentiel reserve aux personnes de 62 ans et plus.',
    profiles: ['senior'],
    yearlyPrice: 633.6,
    monthlyPrice: 52.8,
    zones: { min: 1, max: 5 },
    renewalFrequency: 'annual',
    requiredDocuments: ['identity_document'],
    condition: ({ age }) => (age ?? 0) >= 62,
  },
  {
    id: 'navigo_monthly',
    name: 'Navigo Mois',
    description: 'Un abonnement mensuel sans engagement annuel.',
    profiles: ['employee', 'student', 'senior'],
    yearlyPrice: 1036.8,
    monthlyPrice: 86.4,
    zones: { min: 1, max: 5 },
    renewalFrequency: 'monthly',
    requiredDocuments: [],
    condition: ({ weeklyUsageDays }) => weeklyUsageDays >= 2,
  },
  {
    id: 'navigo_weekly',
    name: 'Navigo Semaine',
    description: 'Une formule du lundi au dimanche pour les besoins ponctuels.',
    profiles: ['employee', 'student', 'senior'],
    yearlyPrice: 1599,
    monthlyPrice: 123,
    zones: { min: 1, max: 5 },
    renewalFrequency: 'weekly',
    requiredDocuments: [],
    condition: ({ weeklyUsageDays }) => weeklyUsageDays <= 3,
  },
  {
    id: 'imagine_r_junior',
    name: 'Imagine R Junior',
    description: 'Pour les enfants de moins de 11 ans.',
    profiles: ['junior_school'],
    yearlyPrice: 418.2,
    monthlyPrice: 34.85,
    zones: { min: 1, max: 5 },
    renewalFrequency: 'annual',
    requiredDocuments: ['family_record', 'school_certificate'],
    condition: ({ age }) => (age ?? 0) < 11,
  },
  {
    id: 'imagine_r_school',
    name: 'Imagine R Scolaire',
    description: 'Pour les eleves de 11 a 25 ans.',
    profiles: ['school'],
    yearlyPrice: 418.2,
    monthlyPrice: 34.85,
    zones: { min: 1, max: 5 },
    renewalFrequency: 'annual',
    requiredDocuments: ['school_certificate'],
    condition: ({ age }) => (age ?? 0) >= 11 && (age ?? 0) <= 25,
  },
  {
    id: 'imagine_r_student',
    name: 'Imagine R Etudiant',
    description: "Pour les etudiants de l'enseignement superieur.",
    profiles: ['student'],
    yearlyPrice: 418.2,
    monthlyPrice: 34.85,
    zones: { min: 1, max: 5 },
    renewalFrequency: 'annual',
    requiredDocuments: ['school_certificate'],
    condition: ({ age }) => (age ?? 0) >= 18 && (age ?? 0) <= 28,
  },
  {
    id: 'liberty_plus',
    name: 'Navigo Liberte+',
    description: "Paiement a l'usage pour les trajets irreguliers.",
    profiles: ['employee', 'student', 'senior'],
    yearlyPrice: null,
    monthlyPrice: null,
    zones: { min: 1, max: 5 },
    renewalFrequency: 'pay_as_you_go',
    requiredDocuments: [],
    condition: ({ weeklyUsageDays }) => weeklyUsageDays <= 2,
  },
  {
    id: 'solidarity_50',
    name: 'TST - Reduction 50%',
    description: 'Aide transport pour les personnes aux revenus modestes.',
    profiles: ['solidarity'],
    yearlyPrice: 518.4,
    monthlyPrice: 43.2,
    zones: { min: 1, max: 5 },
    renewalFrequency: 'quarterly',
    requiredDocuments: ['caf_certificate', 'tax_notice'],
  },
  {
    id: 'solidarity_75',
    name: 'TST - Solidarite 75%',
    description: 'Aide transport avec reduction de 75%.',
    profiles: ['solidarity'],
    yearlyPrice: 259.2,
    monthlyPrice: 21.6,
    zones: { min: 1, max: 5 },
    renewalFrequency: 'quarterly',
    requiredDocuments: ['caf_certificate', 'tax_notice'],
  },
  {
    id: 'solidarity_free',
    name: 'TST - Gratuite',
    description: 'Aide transport avec prise en charge complete.',
    profiles: ['solidarity'],
    yearlyPrice: 0,
    monthlyPrice: 0,
    zones: { min: 1, max: 5 },
    renewalFrequency: 'quarterly',
    requiredDocuments: ['caf_certificate', 'tax_notice'],
  },
  {
    id: 'amethyst',
    name: 'Amethyste',
    description: 'Abonnement pour les personnes reconnues en situation de handicap.',
    profiles: ['amethyst'],
    yearlyPrice: null,
    monthlyPrice: null,
    zones: { min: 1, max: 5 },
    renewalFrequency: 'annual',
    requiredDocuments: ['disability_card', 'mdph_notice'],
  },
]
