import type { Forfait } from '../types/domain'

export const PRIX_TICKET_UNITAIRE = 2.1

export const JUSTIFICATIFS_LABELS: Record<string, string> = {
  piece_identite: "Piece d'identite (CNI, passeport)",
  livret_famille: 'Livret de famille ou acte de naissance',
  certificat_scolarite: 'Certificat de scolarite, annee en cours',
  attestation_bourse: "Attestation d'attribution de bourse",
  attestation_caf: 'Attestation CAF, quotient familial',
  avis_imposition: "Avis d'imposition ou de non-imposition",
  carte_invalidite: "Carte d'invalidite ou notification MDPH",
  notification_mdph: 'Notification de decision MDPH',
}

export const FORFAITS: Forfait[] = [
  {
    id: 'navigo_annuel',
    nom: 'Navigo Annuel',
    description: "L'abonnement annuel tout reseau, ideal pour les usages reguliers.",
    profils: ['salarie', 'etudiant', 'senior'],
    prixAn: 902.4,
    prixMois: 75.2,
    zones: { min: 1, max: 5 },
    renouvellement: 'annuel',
    justificatifsRequis: [],
    condition: ({ joursParSemaine }) => joursParSemaine >= 4,
    remboursementEmployeur: 0.5,
  },
  {
    id: 'navigo_senior',
    nom: 'Navigo Annuel Senior',
    description: 'Tarif preferentiel reserve aux personnes de 62 ans et plus.',
    profils: ['senior'],
    prixAn: 633.6,
    prixMois: 52.8,
    zones: { min: 1, max: 5 },
    renouvellement: 'annuel',
    justificatifsRequis: ['piece_identite'],
    condition: ({ age }) => (age ?? 0) >= 62,
  },
  {
    id: 'navigo_mois',
    nom: 'Navigo Mois',
    description: 'Un abonnement mensuel sans engagement annuel.',
    profils: ['salarie', 'etudiant', 'senior'],
    prixAn: 1036.8,
    prixMois: 86.4,
    zones: { min: 1, max: 5 },
    renouvellement: 'mensuel',
    justificatifsRequis: [],
    condition: ({ joursParSemaine }) => joursParSemaine >= 2,
  },
  {
    id: 'navigo_semaine',
    nom: 'Navigo Semaine',
    description: 'Une formule du lundi au dimanche pour les besoins ponctuels.',
    profils: ['salarie', 'etudiant', 'senior'],
    prixAn: 1599,
    prixMois: 123,
    zones: { min: 1, max: 5 },
    renouvellement: 'hebdomadaire',
    justificatifsRequis: [],
    condition: ({ joursParSemaine }) => joursParSemaine <= 3,
  },
  {
    id: 'imagine_r_junior',
    nom: 'Imagine R Junior',
    description: 'Pour les enfants de moins de 11 ans.',
    profils: ['scolaire_junior'],
    prixAn: 418.2,
    prixMois: 34.85,
    zones: { min: 1, max: 5 },
    renouvellement: 'annuel',
    justificatifsRequis: ['livret_famille', 'certificat_scolarite'],
    condition: ({ age }) => (age ?? 0) < 11,
  },
  {
    id: 'imagine_r_scolaire',
    nom: 'Imagine R Scolaire',
    description: 'Pour les eleves de 11 a 25 ans.',
    profils: ['scolaire'],
    prixAn: 418.2,
    prixMois: 34.85,
    zones: { min: 1, max: 5 },
    renouvellement: 'annuel',
    justificatifsRequis: ['certificat_scolarite'],
    condition: ({ age }) => (age ?? 0) >= 11 && (age ?? 0) <= 25,
  },
  {
    id: 'imagine_r_etudiant',
    nom: 'Imagine R Etudiant',
    description: "Pour les etudiants de l'enseignement superieur.",
    profils: ['etudiant'],
    prixAn: 418.2,
    prixMois: 34.85,
    zones: { min: 1, max: 5 },
    renouvellement: 'annuel',
    justificatifsRequis: ['certificat_scolarite'],
    condition: ({ age }) => (age ?? 0) >= 18 && (age ?? 0) <= 28,
  },
  {
    id: 'liberte_plus',
    nom: 'Navigo Liberte+',
    description: "Paiement a l'usage pour les trajets irreguliers.",
    profils: ['salarie', 'etudiant', 'senior'],
    prixAn: null,
    prixMois: null,
    zones: { min: 1, max: 5 },
    renouvellement: 'usage',
    justificatifsRequis: [],
    condition: ({ joursParSemaine }) => joursParSemaine <= 2,
  },
  {
    id: 'tst_50',
    nom: 'TST - Reduction 50%',
    description: 'Aide transport pour les personnes aux revenus modestes.',
    profils: ['tst'],
    prixAn: 518.4,
    prixMois: 43.2,
    zones: { min: 1, max: 5 },
    renouvellement: 'trimestriel',
    justificatifsRequis: ['attestation_caf', 'avis_imposition'],
  },
  {
    id: 'tst_75',
    nom: 'TST - Solidarite 75%',
    description: 'Aide transport avec reduction de 75%.',
    profils: ['tst'],
    prixAn: 259.2,
    prixMois: 21.6,
    zones: { min: 1, max: 5 },
    renouvellement: 'trimestriel',
    justificatifsRequis: ['attestation_caf', 'avis_imposition'],
  },
  {
    id: 'tst_gratuite',
    nom: 'TST - Gratuite',
    description: 'Aide transport avec prise en charge complete.',
    profils: ['tst'],
    prixAn: 0,
    prixMois: 0,
    zones: { min: 1, max: 5 },
    renouvellement: 'trimestriel',
    justificatifsRequis: ['attestation_caf', 'avis_imposition'],
  },
  {
    id: 'amethyste',
    nom: 'Amethyste',
    description: 'Abonnement pour les personnes reconnues en situation de handicap.',
    profils: ['amethyste'],
    prixAn: null,
    prixMois: null,
    zones: { min: 1, max: 5 },
    renouvellement: 'annuel',
    justificatifsRequis: ['carte_invalidite', 'notification_mdph'],
  },
]
