import type { Forfait } from '../types/domain'
import jourImg from '../assets/images/forfaits/navigo_jour.svg'
import semaineImg from '../assets/images/forfaits/navigo_semaine.png'
import moisImg from '../assets/images/forfaits/navigo_mois.png'
import annuelImg from '../assets/images/forfaits/navigo_annuel.svg'
import libertePlusImg from '../assets/images/forfaits/liberte_plus.svg'
import etudiantImg from '../assets/images/forfaits/imagine_r_etudiant.png'
import scolaireImg from '../assets/images/forfaits/imagine_r_scolaire.png'
import juniorImg from '../assets/images/forfaits/imagine_r_junior.png'

export const PRIX_TICKET_UNITAIRE = 2.10
/** Prix par trajet Navigo Liberté+ — tarif minimum 2026 (varie selon zones). */
export const PRIX_LIBERTE_PLUS_PAR_TRAJET = 1.64
/** URL canonique du catalogue tarifaire IDFM. */
export const IDFM_TARIFS_URL = 'https://www.iledefrance-mobilites.fr/titres-et-tarifs'

/**
 * Catalogue des forfaits Navigo / Imagine R / Solidarité 2026.
 * Source officielle : Île-de-France Mobilités (janvier 2026).
 *
 * Champs clés :
 *  - `type` : périodicité (jour, hebdo, mensuel, annuel, usage)
 *  - `eligible(p)` : prédicat riche basé sur flags (CSS, ASS, AME, RSA, alternant)
 *  - `priorite` : sert au tri par défaut (plus petit = en haut)
 */
export const FORFAITS: Forfait[] = [
  {
    id: 'navigo_jour',
    nom: 'Navigo Jour',
    type: 'jour',
    description: 'Voyager en illimité pendant une journée entière.',
    image: jourImg,
    priorite: 60,
    sourceUrl: IDFM_TARIFS_URL,
    profils: ['salarie', 'etudiant', 'senior'],
    prixAn: null,
    prixMois: null,
    zones: { min: 1, max: 5 },
    renouvellement: 'jour',
    justificatifsRequis: [],
    condition: ({ joursParSemaine }) => joursParSemaine <= 1,
    eligible: () => true,
  },
  {
    id: 'navigo_semaine',
    nom: 'Navigo Semaine',
    type: 'hebdo',
    description: 'Voyager en illimité toute la semaine.',
    image: semaineImg,
    priorite: 50,
    sourceUrl: IDFM_TARIFS_URL,
    profils: ['salarie', 'etudiant', 'senior'],
    prixAn: 32.40 * 52,
    prixMois: 32.40 * (52 / 12),
    zones: { min: 1, max: 5 },
    renouvellement: 'hebdomadaire',
    justificatifsRequis: [],
    condition: ({ joursParSemaine }) => joursParSemaine <= 3,
    eligible: () => true,
  },
  {
    id: 'navigo_mois',
    nom: 'Navigo Mois',
    type: 'mensuel',
    description: 'Voyager en illimité tout le mois, sans engagement.',
    image: moisImg,
    priorite: 40,
    sourceUrl: IDFM_TARIFS_URL,
    profils: ['salarie', 'etudiant', 'senior'],
    prixAn: 1089.60,
    prixMois: 90.80,
    zones: { min: 1, max: 5 },
    renouvellement: 'mensuel',
    justificatifsRequis: [],
    condition: ({ joursParSemaine }) => joursParSemaine >= 2,
    eligible: () => true,
    remboursementEmployeur: 0.5,
  },
  {
    id: 'navigo_annuel',
    nom: 'Navigo Annuel',
    type: 'annuel',
    description: 'Voyager toute l\'année — le 12ᵉ mois offert.',
    image: annuelImg,
    priorite: 30,
    sourceUrl: IDFM_TARIFS_URL,
    profils: ['salarie', 'etudiant', 'senior'],
    prixAn: 90.80 * 11,
    prixMois: 90.80,
    zones: { min: 1, max: 5 },
    renouvellement: 'annuel',
    justificatifsRequis: [],
    condition: ({ joursParSemaine }) => joursParSemaine >= 4,
    eligible: () => true,
    remboursementEmployeur: 0.5,
  },
  {
    id: 'navigo_senior',
    nom: 'Navigo Senior',
    type: 'annuel',
    description: 'Tarif préférentiel pour les 62 ans et plus.',
    image: null,
    priorite: 25,
    sourceUrl: IDFM_TARIFS_URL,
    profils: ['senior'],
    prixAn: 544.80,
    prixMois: 45.40,
    zones: { min: 1, max: 5 },
    renouvellement: 'annuel',
    justificatifsRequis: ['piece_identite'],
    condition: ({ age }) => (age ?? 0) >= 62,
    eligible: ({ age, flags }) => (age ?? 0) >= 62 || !!flags?.isRetraite,
  },
  {
    id: 'imagine_r_etudiant',
    nom: 'Imagine R Étudiant',
    type: 'annuel',
    description: 'Le forfait indispensable des étudiants en Île-de-France.',
    image: etudiantImg,
    priorite: 20,
    sourceUrl: IDFM_TARIFS_URL,
    profils: ['etudiant'],
    prixAn: 392.30,
    prixMois: 392.30 / 12,
    zones: { min: 1, max: 5 },
    renouvellement: 'annuel',
    justificatifsRequis: ['certificat_scolarite'],
    condition: ({ age }) => (age ?? 0) >= 18 && (age ?? 0) <= 25,
    eligible: ({ age, flags }) => !!flags?.isEtudiant && (age ?? 0) < 26,
  },
  {
    id: 'imagine_r_scolaire',
    nom: 'Imagine R Scolaire',
    type: 'annuel',
    description: 'Le forfait annuel des jeunes du primaire, secondaire et apprentis.',
    image: scolaireImg,
    priorite: 20,
    sourceUrl: IDFM_TARIFS_URL,
    profils: ['scolaire'],
    prixAn: 392.30,
    prixMois: 392.30 / 12,
    zones: { min: 1, max: 5 },
    renouvellement: 'annuel',
    justificatifsRequis: ['certificat_scolarite'],
    condition: ({ age }) => (age ?? 0) >= 11 && (age ?? 0) <= 25,
    eligible: ({ age, flags }) => (age ?? 0) >= 11 && (age ?? 0) < 26 && (!!flags?.isAlternant || !flags?.isEtudiant),
  },
  {
    id: 'imagine_r_junior',
    nom: 'Imagine R Junior',
    type: 'annuel',
    description: 'imagine R à un prix imbattable pour les moins de 11 ans.',
    image: juniorImg,
    priorite: 20,
    sourceUrl: IDFM_TARIFS_URL,
    profils: ['scolaire_junior'],
    prixAn: 24.80,
    prixMois: 24.80 / 12,
    zones: { min: 1, max: 5 },
    renouvellement: 'annuel',
    justificatifsRequis: ['livret_famille', 'certificat_scolarite'],
    condition: ({ age }) => (age ?? 0) < 11,
    eligible: ({ age }) => (age ?? 0) < 11,
  },
  {
    id: 'liberte_plus',
    nom: 'Navigo Liberté+',
    type: 'usage',
    description: 'Payez vos trajets à l\'unité — dès 1,64 € par trajet, toutes zones.',
    image: libertePlusImg,
    priorite: 45,
    sourceUrl: IDFM_TARIFS_URL,
    profils: ['salarie', 'etudiant', 'senior'],
    prixAn: null,
    prixMois: null,
    zones: { min: 1, max: 5 },
    renouvellement: 'usage',
    justificatifsRequis: [],
    condition: ({ joursParSemaine }) => joursParSemaine <= 2,
    eligible: () => true,
  },
  {
    id: 'navigo_solidarite_75',
    nom: 'Solidarité 75 %',
    type: 'mensuel',
    description: 'Réduction de 75 % pour les bénéficiaires CSS sans participation ou ASS.',
    image: null,
    priorite: 15,
    sourceUrl: IDFM_TARIFS_URL,
    profils: ['tst'],
    prixAn: 22.70 * 12,
    prixMois: 22.70,
    zones: { min: 1, max: 5 },
    renouvellement: 'mensuel',
    justificatifsRequis: ['attestation_caf', 'avis_imposition'],
    eligible: ({ flags }) => !!flags?.hasCSSSansParticipation || !!flags?.hasASS,
  },
  {
    id: 'navigo_reduction_50',
    nom: 'Réduction 50 %',
    type: 'mensuel',
    description: 'Réduction de 50 % pour les bénéficiaires AME.',
    image: null,
    priorite: 18,
    sourceUrl: IDFM_TARIFS_URL,
    profils: ['tst'],
    prixAn: 45.40 * 12,
    prixMois: 45.40,
    zones: { min: 1, max: 5 },
    renouvellement: 'mensuel',
    justificatifsRequis: ['attestation_caf', 'avis_imposition'],
    eligible: ({ flags }) => !!flags?.hasAME,
  },
  {
    id: 'navigo_gratuite',
    nom: 'Gratuité Transport',
    type: 'mensuel',
    description: 'Transport gratuit pour les bénéficiaires RSA sous conditions ou ASS + CSS sans participation.',
    image: null,
    priorite: 10,
    sourceUrl: IDFM_TARIFS_URL,
    profils: ['tst'],
    prixAn: 0,
    prixMois: 0,
    zones: { min: 1, max: 5 },
    renouvellement: 'mensuel',
    justificatifsRequis: ['attestation_caf', 'avis_imposition'],
    eligible: ({ flags }) => !!flags?.hasRSA || (!!flags?.hasASS && !!flags?.hasCSSSansParticipation),
  },
  {
    id: 'amethyste',
    nom: 'Améthyste',
    type: 'annuel',
    description: 'Forfait pour les personnes en situation de handicap (selon département).',
    image: null,
    priorite: 22,
    sourceUrl: IDFM_TARIFS_URL,
    profils: ['amethyste'],
    prixAn: null,
    prixMois: null,
    zones: { min: 1, max: 5 },
    renouvellement: 'annuel',
    justificatifsRequis: ['carte_invalidite', 'notification_mdph'],
    eligible: () => true,
  },
]
