import type { Plan } from './domain'

export const SINGLE_TICKET_PRICE = 2.10
export const LIBERTE_PLUS_PRICE_PER_TRIP = 1.64
export const IDFM_FARES_URL = 'https://www.iledefrance-mobilites.fr/titres-et-tarifs'

export const PLANS: Plan[] = [
  {
    id: 'navigo_day',
    name: 'Navigo Jour',
    type: 'day',
    description: 'Voyager en illimite pendant une journee entiere.',
    image: null,
    priority: 60,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['employee', 'student', 'senior'],
    yearlyPrice: null,
    monthlyPrice: null,
    zones: { min: 1, max: 5 },
    renewal: 'day',
    requiredDocuments: [],
    condition: ({ daysPerWeek }) => daysPerWeek <= 1,
    eligible: () => true,
  },
  {
    id: 'navigo_week',
    name: 'Navigo Semaine',
    type: 'weekly',
    description: 'Voyager en illimite toute la semaine.',
    image: null,
    priority: 50,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['employee', 'student', 'senior'],
    yearlyPrice: 32.40 * 52,
    monthlyPrice: 32.40 * (52 / 12),
    zones: { min: 1, max: 5 },
    renewal: 'weekly',
    requiredDocuments: [],
    condition: ({ daysPerWeek }) => daysPerWeek <= 3,
    eligible: () => true,
  },
  {
    id: 'navigo_month',
    name: 'Navigo Mois',
    type: 'monthly',
    description: 'Voyager en illimite tout le mois, sans engagement annuel.',
    image: null,
    priority: 40,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['employee', 'student', 'senior'],
    yearlyPrice: 1089.60,
    monthlyPrice: 90.80,
    zones: { min: 1, max: 5 },
    renewal: 'monthly',
    requiredDocuments: [],
    condition: ({ daysPerWeek }) => daysPerWeek >= 2,
    eligible: () => true,
    employerRefund: 0.5,
  },
  {
    id: 'navigo_yearly',
    name: 'Navigo Annuel',
    type: 'yearly',
    description: "Voyager toute l'annee avec le 12e mois inclus.",
    image: null,
    priority: 30,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['employee', 'student', 'senior'],
    yearlyPrice: 90.80 * 11,
    monthlyPrice: 90.80,
    zones: { min: 1, max: 5 },
    renewal: 'yearly',
    requiredDocuments: [],
    condition: ({ daysPerWeek }) => daysPerWeek >= 4,
    eligible: () => true,
    employerRefund: 0.5,
  },
  {
    id: 'navigo_senior',
    name: 'Navigo Senior',
    type: 'yearly',
    description: 'Tarif preferentiel pour les 62 ans et plus.',
    image: null,
    priority: 25,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['senior'],
    yearlyPrice: 544.80,
    monthlyPrice: 45.40,
    zones: { min: 1, max: 5 },
    renewal: 'yearly',
    requiredDocuments: ['identity_document'],
    condition: ({ age }) => (age ?? 0) >= 62,
    eligible: ({ age, flags }) => (age ?? 0) >= 62 || !!flags?.isRetired,
  },
  {
    id: 'imagine_r_student',
    name: 'Imagine R Etudiant',
    type: 'yearly',
    description: 'Le forfait indispensable des etudiants en Ile-de-France.',
    image: null,
    priority: 20,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['student'],
    yearlyPrice: 392.30,
    monthlyPrice: 392.30 / 12,
    zones: { min: 1, max: 5 },
    renewal: 'yearly',
    requiredDocuments: ['school_certificate'],
    condition: ({ age }) => (age ?? 0) >= 18 && (age ?? 0) <= 25,
    eligible: ({ age, flags }) => !!flags?.isStudent && (age ?? 0) < 26,
  },
  {
    id: 'imagine_r_school',
    name: 'Imagine R Scolaire',
    type: 'yearly',
    description: 'Le forfait annuel des jeunes du primaire, du secondaire et des apprentis.',
    image: null,
    priority: 20,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['school'],
    yearlyPrice: 392.30,
    monthlyPrice: 392.30 / 12,
    zones: { min: 1, max: 5 },
    renewal: 'yearly',
    requiredDocuments: ['school_certificate'],
    condition: ({ age }) => (age ?? 0) >= 11 && (age ?? 0) <= 25,
    eligible: ({ age, flags }) => (age ?? 0) >= 11 && (age ?? 0) < 26 && (!!flags?.isApprentice || !flags?.isStudent),
  },
  {
    id: 'imagine_r_junior',
    name: 'Imagine R Junior',
    type: 'yearly',
    description: 'Imagine R a un prix tres avantageux pour les moins de 11 ans.',
    image: null,
    priority: 20,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['junior_school'],
    yearlyPrice: 24.80,
    monthlyPrice: 24.80 / 12,
    zones: { min: 1, max: 5 },
    renewal: 'yearly',
    requiredDocuments: ['family_record_book', 'school_certificate'],
    condition: ({ age }) => (age ?? 0) < 11,
    eligible: ({ age }) => (age ?? 0) < 11,
  },
  {
    id: 'liberty_plus',
    name: 'Navigo Liberte+',
    type: 'usage',
    description: "Payez vos trajets a l'unite, des 1,64 EUR par trajet, toutes zones.",
    image: null,
    priority: 45,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['employee', 'student', 'senior'],
    yearlyPrice: null,
    monthlyPrice: null,
    zones: { min: 1, max: 5 },
    renewal: 'usage',
    requiredDocuments: [],
    condition: ({ daysPerWeek }) => daysPerWeek <= 2,
    eligible: () => true,
  },
  {
    id: 'navigo_solidarity_75',
    name: 'Solidarite 75%',
    type: 'monthly',
    description: 'Reduction de 75% pour les beneficiaires CSS sans participation ou ASS.',
    image: null,
    priority: 15,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['solidarity'],
    yearlyPrice: 22.70 * 12,
    monthlyPrice: 22.70,
    zones: { min: 1, max: 5 },
    renewal: 'monthly',
    requiredDocuments: ['caf_certificate', 'tax_notice'],
    eligible: ({ flags }) => !!flags?.hasCssWithoutCopay || !!flags?.hasASS,
  },
  {
    id: 'navigo_discount_50',
    name: 'Reduction 50%',
    type: 'monthly',
    description: 'Reduction de 50% pour les beneficiaires AME.',
    image: null,
    priority: 18,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['solidarity'],
    yearlyPrice: 45.40 * 12,
    monthlyPrice: 45.40,
    zones: { min: 1, max: 5 },
    renewal: 'monthly',
    requiredDocuments: ['caf_certificate', 'tax_notice'],
    eligible: ({ flags }) => !!flags?.hasAME,
  },
  {
    id: 'navigo_free',
    name: 'Gratuite Transport',
    type: 'monthly',
    description: 'Transport gratuit pour les beneficiaires RSA eligibles.',
    image: null,
    priority: 10,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['solidarity'],
    yearlyPrice: 0,
    monthlyPrice: 0,
    zones: { min: 1, max: 5 },
    renewal: 'monthly',
    requiredDocuments: ['caf_certificate', 'tax_notice'],
    eligible: ({ flags }) => !!flags?.hasRSA || (!!flags?.hasASS && !!flags?.hasCssWithoutCopay),
  },
  {
    id: 'amethyst',
    name: 'Amethyste',
    type: 'yearly',
    description: 'Forfait pour les personnes en situation de handicap, selon le departement.',
    image: null,
    priority: 22,
    sourceUrl: IDFM_FARES_URL,
    profiles: ['amethyst'],
    yearlyPrice: null,
    monthlyPrice: null,
    zones: { min: 1, max: 5 },
    renewal: 'yearly',
    requiredDocuments: ['disability_card', 'mdph_notice'],
    eligible: () => true,
  },
]
